kind: pipeline
# type: kubernetes
name: playground-app

# platform:
#   os: linux
#   arch: arm64

steps:
- name: greeting
  image: node:20.11.1-alpine
  # commands:
  # - echo hello
  # - echo world
  # neat
