kind: pipeline
type: docker
name: default 

steps:
  - name: setup
    image: node:14-alpine
    commands: 
      - apk add --no-cache docker
      - npm install
      - npm run build  

  - name: build-docker-image
    image: docker:20.10.7
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DRONE_SERVER_IP:
        from_secret: DRONE_SERVER_IP 
    commands:
      - echo "Building Neat Docker image"   
      #- echo $DRONE_SERVER_IP
      - docker build -t playground-app:latest . 
      - docker tag playground-app:latest $DRONE_SERVER_IP:5000/playground-app:latest
      - docker push $DRONE_SERVER_IP:5000/playground-app:latest
 
  - name: deploy
    image: appleboy/drone-ssh 
    settings:
      host: 
        from_secret: k8s_server_ip
      port: 22
      username: 
        from_secret: ssh_username
      key:
        from_secret: ssh_private_key
      script:  
        - echo "Checking current directory contents"
        - ls -la
        - kubectl apply -f deployment.yml
        - kubectl apply -f service.yml 

  # - name: deploy
  #   image: target/kubernetes
  #   settings:
  #     manifests:
  #       - deployment.yaml
  #       - service.yaml
  #   environment:
  #     KUBE_CONFIG:
  #       from_secret: kubeconfig
      # context: kubernetes-admin@kubernetes
      # KUBE_CONTEXT: kubernetes-admin@kubernetes


  # - name: deploy
  #   image:
  #     from_secret: $DRONE_SERVER_IP:5000/playground-app:latest
  #   commands:
  #     - kubectl apply -f deployment.yml
  #     - kubectl apply -f services.yml
  #   environment: 
  #     DRONE_SERVER_IP:
  #       from_secret: DRONE_SERVER_IP
  #     KUBECONFIG: /root/.kube/config  # This is the path inside the container
  #   volumes:
  #     - name: kubeconfig
  #       path: /root/.kube  # Mount point inside the container 
  

  # - name: debug
  #   image: busybox
  #   commands:
  #     - ls -al 

  # - name: deploy
  #   image: appleboy/drone-ssh 
  #   settings:
  #     host: 
  #       from_secret: k8s_server_ip
  #     port: 22
  #     username: 
  #       from_secret: ssh_username
  #     key:
  #       from_secret: ssh_private_key
  #     script:
  #       - ls -la
  #       #- docker pull samuelbarone/playground-app:latest
  #       - kubectl apply -f deployment.yml
  #       - kubectl apply -f service.yml  


      # - docker build -t playground-app:latest . 
      # - docker push playground-app:latest  # Push the image to the registry 
      # - docker tag playground-app:latest localhost:5000/playground-app:latest 
      # - docker info  # Check if Docker daemon is accessible 
      # - docker build -t samuelbarone/playground-app:latest . 
      
  # - name: display-working-directory
  #   image: alpine:3.14
  #   commands:
  #     - echo "Current working directory:"
  #     - pwd
  #     - ls -la
 
  # - name: deploy
  #   image: appleboy/drone-ssh 
  #   settings:
  #     host: 
  #       from_secret: k8s_server_ip
  #     port: 22
  #     username: 
  #       from_secret: ssh_username
  #     key:
  #       from_secret: ssh_private_key
  #     script: 
  #       #- git clone https://github.com/samuelbarone/playground-app
  #       #- cd /tmp/repo
  #       - echo "Checking current directory contents"
  #       - ls -la
  #       - kubectl apply -f deployment.yml
  #       - kubectl apply -f service.yml  



 
  # - name: copy-yaml-files
  #   image: alpine
  #   commands:
  #     - ls -la
  #     - cp deployment.yml /drone/src/deployment.yml
  #     - cp service.yml /drone/src/service.yml

  # - name: deploy-to-kubernetes
  #   image: appleboy/drone-ssh
  #   settings:
  #     host:
  #       from_secret: k8s_server_ip
  #     port: 22
  #     username:
  #       from_secret: ssh_username
  #     key:
  #       from_secret: ssh_private_key
  #     script:
  #       - ls -la
  #       - kubectl apply -f /drone/src/deployment.yaml
  #       - kubectl apply -f /drone/src/service.yaml

 
  # - name: debug
  #   image: appleboy/drone-ssh
  #   settings:
  #     host:
  #       from_secret: k8s_server_ip
  #     port: 22
  #     username:
  #       from_secret: ssh_username
  #     key:
  #       from_secret: ssh_private_key
  #     commands:
  #       - echo "Checking current directory contents"
  #       - ls -la
  #       - ls -la /drone/src
  #       - ls -la /app
  #       - cat /drone/src/deployment.yml  # Check if file is readable
  #       - echo "NEAT"
  #       - kubectl apply -f /drone/src/deployment.yaml
  #       - kubectl apply -f /drone/src/service.yaml
 
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock