kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:14-alpine
    commands: 
      - apk add --no-cache docker
      - npm install
      - npm run build  

  - name: build-docker-image
    image: docker:20.10.7
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Building Docker image" 
      - echo "Docker username secret **** ${k8s_server_ip} ****"
      - docker info  # Check if Docker daemon is accessible
      - docker build -t playground-app . 

  - name: display-working-directory
    image: alpine:3.14
    commands:
      - echo "Current working directory:"
      - pwd
      - ls -la
 
  - name: deploy
    image: appleboy/drone-ssh 
    settings:
      host: 
        from_secret: k8s_server_ip
      port: 22
      username: 
        from_secret: ssh_username
      key:
        from_secret: ssh_private_key
      script: 
        #- git clone https://github.com/samuelbarone/playground-app
        #- cd /tmp/repo
        - kubectl apply -f deployment.yml
        - kubectl apply -f service.yml  

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock