# .drone.yml
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:20.11.1-alpine
  commands:
    - npm install
    - npm run build
    - docker build -t samuelbarone/playground-app:latest .

- name: test
  image: node:20.11.1-alpine
  commands:
    - npm test  
 
- name: docker-build
  image: docker:stable
  commands:
    - docker build -t samuelbarone/playground-app:latest .
    - echo "$ssh_private_key" | docker login -u "$ssh-username" --password-stdin
    - docker push samuelbarone/playground-app:latest

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: k8s_server_ip
    username: ssh-username
    key:
      from_secret: ssh_private_key
    script:
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

services:
- name: docker
  image: docker:dind
  privileged: true

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock