kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:14-alpine
    commands: 
      - apk add --no-cache docker
      - npm install
      - npm run build  

  - name: build-docker-image
    image: docker:20.10.7
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Building Docker image" 
      - docker build -t playground-app .
      # - docker tag playground-app:latest localhost:5000/playground-app:latest
      #- echo "Docker username secret **** ${k8s_server_ip} ****"
      #- docker info  # Check if Docker daemon is accessible
      #- docker build -t playground-app . 
      # - docker build -t samuelbarone/playground-app:latest .
      # - docker push samuelbarone/playground-app:latest  # Push the image to the registry
 

  # - name: display-working-directory
  #   image: alpine:3.14
  #   commands:
  #     - echo "Current working directory:"
  #     - pwd
  #     - ls -la
 
  # - name: deploy
  #   image: appleboy/drone-ssh 
  #   settings:
  #     host: 
  #       from_secret: k8s_server_ip
  #     port: 22
  #     username: 
  #       from_secret: ssh_username
  #     key:
  #       from_secret: ssh_private_key
  #     script: 
  #       #- git clone https://github.com/samuelbarone/playground-app
  #       #- cd /tmp/repo
  #       - echo "Checking current directory contents"
  #       - ls -la
  #       - kubectl apply -f deployment.yml
  #       - kubectl apply -f service.yml  



 
  - name: copy-yaml-files
    image: alpine
    commands:
      - ls -la
      - cp deployment.yml /drone/src/deployment.yml
      - cp service.yml /drone/src/service.yml

  - name: deploy-to-kubernetes
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: k8s_server_ip
      port: 22
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_private_key
      script:
        - ls -la
        - kubectl apply -f /drone/src/deployment.yaml
        - kubectl apply -f /drone/src/service.yaml

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock