# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  label:
    app: playground-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: playground-app
        image: 10.0.0.69:5000/playground-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
